const EXPIRES_IN_ONE_WEEK = 60 * 60 * 24 * 7;
const USER_SCHEMA_NAME = 'User';
const PRODUCT_SCHEMA_NAME = 'Product';
const SINGLE_IMAGE = 'image';

const PASSWORD_FIELD = 'password';
const SALT_ROUNDS = 10;

const DATABASE_ID_PATH = '_id';

export {
  EXPIRES_IN_ONE_WEEK,
  USER_SCHEMA_NAME,
  PRODUCT_SCHEMA_NAME,
  SINGLE_IMAGE,
  PASSWORD_FIELD,
  SALT_ROUNDS,
  DATABASE_ID_PATH,
};
