name: Build and Deploy

on:
  push:
    branches: [ "preprod" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install deps
        run: npm ci
      - name: Lint app
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install deps
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Upload build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build files
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy to AWS-ECR
        run: |
          ls -la ./dist
          docker build -t aroma-api ./dist
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_URL }}
          docker tag aroma-api:latest ${{ secrets.AWS_ECR_URL }}:latest
          docker push ${{ secrets.AWS_ECR_URL }}:latest
          aws ecs update-service --cluster ${{ secrets.AWS_CLUSTER_NAME }} --service ${{ secrets.AWS_SERVICE_NAME }} --force-new-deployment --region ${{ secrets.AWS_REGION }}